# Use an official Node.js image as the base image.
FROM 161805785056.dkr.ecr.us-east-1.amazonaws.com/testing:latest

# Set the working directory in the container
WORKDIR /usr/local/apache2/htdocs/

# Copy package.json and package-lock.json to the working directory
COPY ./abrapache/index.html ./
